FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o bin/migrate ./cmd/migrate/main.go

ENTRYPOINT ["./bin/migrate", "up"]
